### ISSUE TITLE
Migrate from LALRPOP to Pest

### ISSUE THREAD

**Issue by adam-mcdaniel** [adam-mcdaniel/sage#40]
LALRPOP has been a pain. Use Pest instead. Right now the frontend uses Pest, and the stages of IR use LALRPOP.

**Comment by adam-mcdaniel** [comment]
This was fixed a long while ago! Although now we're switching to nom instead.

**Comment by aaronvg** [comment]
What made you switch to nom? Did you find Pest easier to use than lalrpop?
