### ISSUE TITLE
FFI acronym in readme.md may be unrecognized

### ISSUE THREAD

**Issue by macginitie** [adam-mcdaniel/sage#67]
... or, maybe I'm the only person interested in computer programming languages who doesn't know what FFI stands for. In which case, just close this issue, I guess. I actually suspect that might be true, and didn't even look to see if anyone had opened an equivalent issue, because I thought it very unlikely. The trouble with "just [search] it" is that it's work, even if not very much.

**Comment by adam-mcdaniel** [comment]
Okay, I'll replace it with "foreign function interface!"

**Comment by adam-mcdaniel** [comment]
Fixed with #68!
